### PR TITLE
Fix NoteBlock sound (#8)

### PR DESCRIPTION
**Pull request by MalakasPlayzMC**
I have fixed the bug with the noteblock sound (#8)

### CODE REVIEW

**Comment by NFGamerMC** [comment]
Please do not copy code

**Comment by NFGamerMC** [comment]
Please write your own code, or steal from Genisys and PMMP.

**Comment by MalakasPlayzMC** [comment]
There is not other way to make noteblock to work. Its simple math. If someone say that 2 plus 2 does 4 and an other man say the same think, does not means that he copied his answer

**Comment by NFGamerMC** [comment]
Write your own code though, we are from Custom Code, Genisys, and PMMP only!

**Comment by AppleDevelops** [comment]
"Steal from PMMP and Genisys" Not cool NF

**Comment by NFGamerMC** [comment]
@AppleDevelops What I meant is that Arufa is code from Genisys and PMMP. Not to steal it but to modify as that is what we are based on.

**Comment by AppleDevelops** [comment]
If this works, I will accept the PR, I don't like copy and pasted code, but I'll accept it.

**Comment by NFGamerMC** [comment]
@AppleDevelops Have a look at the other PR, it is not copied

**Pull request closed without merging**
