### PR TITLE
Change the MINECRAFT_VERSION_NETWORK from  1.0.8.0 to 1.0.8

### PR DESCRIPTION
**Pull request by MalakasPlayzMC**

### CODE REVIEW

**Comment by NFGamerMC** [comment]
Have you tested this, I know that is a stupid question but it is required

**Comment by MalakasPlayzMC** [comment]
This sets the what version will be shown in the server motd. Eg. Something Craft network - v1.0.8.0 will be shown as Something Craft network - v1.0.8
So I think it is not required to test this. By the way MCPE clients join the server with the protocol version not the version. MINECRAFT_VERSION I think sets the version will be shown when you run the /version command

**Comment by TheRoyalBlock** [comment]
Yeah, there is really no need to test this.

**Comment by NFGamerMC** [comment]
What you are telling me is already implemented, it helps for some users and it does not affect anyone on the front end

**Comment by TheRoyalBlock** [comment]
It's a 100% useless pull request, which is why it does not need to be tested. That's what I was trying to say.

**Pull request closed without merging**
