### PR TITLE
ASCII and Licence Changes (only Block)

### PR DESCRIPTION
**Pull request by NFGamerMC**
This is just me trying to change everything over to Arufa. Please do not merge until complete

### CODE REVIEW

**Comment by TheRoyalBlock** [comment]
You should remove all of the ascii.

**Comment by NFGamerMC** [comment]
@TheRoyalBlock Why? People may take our code and it is better for people to know who created it.

**Comment by AppleDevelops** [comment]
Do not do this, you're violating many things

**Comment by AppleDevelops** [comment]
@TheRoyalBlock I'm still not doing anything you recommend

**Comment by TheRoyalBlock** [comment]
Except this one thing: Pocketmine license states that the **same licence must be used**, something that has not been done with this software. That should be changed.

**Pull request merged**
