### PR TITLE
Fix of noteblocks from malakasplayz with genisys logo

### PR DESCRIPTION
**Pull request by poustmal**

### CODE REVIEW

**Comment by poustmal** [comment]
It will seem a bit like its not full copy paste.idk

**Comment by NFGamerMC** [comment]
Testing Now...

**Comment by poustmal** [comment]
works

**Comment by NFGamerMC** [comment]
Did you write this code yourself?

**Comment by poustmal** [comment]
no

**Comment by poustmal** [comment]
I copied the changes of other pull request and add it to make it seem same without bluelight logo

**Comment by NFGamerMC** [comment]
You cannot do that, that voids the license. You also cannot copy code from another PR

**Pull request closed without merging**
